name             'course_app'
maintainer       'Edmund Haselwanter'
maintainer_email 'ehaselwanter@iteh.at'
license          'All rights reserved'
description      'Installs/Configures course_app'
long_description 'Installs/Configures course_app'
version          '0.1.13'

depends 'apt', '2.6.0'
depends 'rbenv', '1.7.1'
depends 'passenger_apache2', '2.2.2'
depends 'artifact', '1.12.2'
